name: basic-checks

on:
  push:
    branches-ignore:
    - please-do-not-ignore-any-branches

jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: newline-checks
      run: |
        set +x
        set +e
        err=0
        while read -r file; do
          [[ -f "$file" ]] || continue
          wc="$(wc -l < "$file")"
          awk="$(< "$file" awk 'BEGIN{lc=0}{lc++}END{print lc}')"
          if [[ "$wc" != "$awk" ]]; then
            (( err++ ))
            echo ":: $file: No newline at end of file."
            echo >> "$file"
          fi
        done < <( \
          find . -type f -iname "*.sh" -o -iname "*.md")
        [[ $err -eq 0 ]]

    - name: shellcheck
      run: |
        set +x
        set +e
        wget --quiet -c https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz
        tar xJf shellcheck-v0.7.1.linux.x86_64.tar.xz
        export PATH=$(pwd -P)/shellcheck-v0.7.1/:$PATH
        while read -r file; do
          echo >&2 ":: Checking $file..."
          shellcheck "$file" || exit
        done < <( \
          find \
          -type f -iname "*.sh" \
        )
